codeml:
  M0HKY:
    noisy: 0
    verbose: 1
    runmode: 0
    seqtype: 1
    clock: 0
    aaDist: 0
    model: 0
    icode: 0
    Mgene: 0
    fix_kappa: 0
    kappa: 2
    fix_alpha: 1
    alpha: 0
    Malpha: 0
    getSE: 0
    RateAncestor: 0
    fix_blength: 0
    method: 0
    Small_Diff: 0.45e-6
    cleandata: 0
    CodonFreq: 4
    NSsites: 0
    ncatG: 10
    omega: 1
    hkyREV: 0
    estFreq: 0
  M7HKY:
    noisy: 0
    verbose: 1
    runmode: 0
    seqtype: 1
    clock: 0
    aaDist: 0
    model: 0
    icode: 0
    Mgene: 0
    fix_kappa: 0
    kappa: 2
    fix_alpha: 1
    alpha: 0
    Malpha: 0
    getSE: 0
    RateAncestor: 0
    fix_blength: 0
    method: 0
    Small_Diff: 0.45e-6
    cleandata: 0
    CodonFreq: 4
    NSsites: 7
    ncatG: 10
    omega: 1
    hkyREV: 0
    estFreq: 0
  M8HKY:
    noisy: 0
    verbose: 1
    runmode: 0
    seqtype: 1
    clock: 0
    aaDist: 0
    model: 0
    icode: 0
    Mgene: 0
    fix_kappa: 0
    kappa: 2
    fix_alpha: 1
    alpha: 0
    Malpha: 0
    getSE: 0
    RateAncestor: 0
    fix_blength: 0
    method: 0
    Small_Diff: 0.45e-6
    cleandata: 0
    CodonFreq: 4
    NSsites: 8
    ncatG: 10
    omega: 1
    hkyREV: 0
    estFreq: 0
