run:
  GENEID: ['TNFAIP3', 'MEP1A', 'STRIP1', 'MYB', 'GPAM', 'SEMA3D', 'WDR91', 'PDE6A', 'CSRP2BP', 'HSPA4']
test:
  GENEID: ['TNFAIP3', 'MEP1A', 'STRIP1', 'MYB', 'GPAM', 'SEMA3D', 'WDR91', 'PDE6A', 'CSRP2BP', 'HSPA4']
